owner: aharooms # Your GitHub username
repo: upptime # Your GitHub repository name
user-agent: namnhce
runner: self-hosted
# Add your sites here
sites:
  - name: Aharooms
    url: https://www.aharooms.com
  - name: Aharooms Admin
    url: https://admin.aharooms.com
  - name: PMS Aharooms
    url: https://pms.aharooms.com
  - name: Metabase
    url: https://base.aharooms.com
  - name: API version 1
    url: https://be.aharooms.com/healthz
  - name: API version 2
    url: https://api.aharooms.com/healthz
assignees: # Users to assign downtime issues (optional)
  - namnhce
  - zlatanpham
status-website:
  # publish: true
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.aharooms.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  favicon: https://s3.aharooms.net/resources/aha-logo.png
  logoUrl: https://s3.aharooms.net/resources/aha-logo.png
  name: Status
  introMessage: This is the status page which uses real-time data from Aharooms services.
i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  uptime: "*/2 * * * *"
